services:
  eventreservation-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventreservation-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1434:1433"
    volumes:
      - eventreservation_sql_data:/var/opt/mssql

volumes:
  eventreservation_sql_data: